### ISSUE TITLE
juliaEval results in Error in runJuliaServer()

### ISSUE THREAD

**Issue by jgoodman55** [stefan-m-lenz/JuliaConnectoR#4] opened 2021-01-21 21:57 UTC
Hello, I've been trying to run the following code and I get the error below.

library(Rserve)

f2 <- juliaEval('function f2(x)
                x .^2
                end')
Starting Julia ...
Error in runJuliaServer() : 
  Timeout while waiting for response from Julia server

Any advice on what I should do?

**Comment by stefan-m-lenz** [comment] 2021-01-23 13:10
One explanation could be that Julia did not start properly or it crashed while starting. Which version of Julia are you using?

Another explanation could be that you have some firewall settings that prevent incoming connections. Which system are you using? Do you have a firewall enabled?

**Comment by stefan-m-lenz** [comment] 2021-01-23 14:50
I just tried it on my new Windows computer for the first time and could reproduce this issue. I tracked down the bug on my computer. On my computer the problem was that my user name has a blank space in it, which my other user names on the other computers don't have. This blank resulted in an error when executing the Julia startup script due to unquoted file paths.
I fixed this issue in the branch FixIssueNo4. Could you please try out if this solves the issue for you also?
For this, please install the `JuliaConnectoR` from the new GitHub branch:

    devtools::install_github("stefan-m-lenz/JuliaConnectoR", ref = "FixIssueNo4")

Thank you very much for reporting this in any case. I will merge this fix into the master branch as soon as I have fixed some new travis issues with R 3.2.

**Comment by jgoodman55** [comment] 2021-01-23 20:39
Hello,

Thank you for getting back to me. I believe I’ve been using Julia 1.5.3 on a Windows computer. I think the issue is likely related to firewall settings, but would that be my computer’s settings or settings specific to Julia or R? Any idea what the setting would be that I need to change? I also have not been using the developer version of the package. Is that necessary for the package to work properly? As far as I know, there’s no space in my username, but I will check that out.

I’m new to GitHub, so maybe I didn’t install everything that I should have? I only installed the package through R. I didn’t download or install anything from your GitHub page. Is there anything I need to do besides install the JuliaConnectoR package?

Thanks for your help!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by stefan-m-lenz** [comment] 2021-01-23 20:55
No, the CRAN version is supposed to work. The only other thing you need to install is Julia itself.

But it seems that you have discovered a bug. I fixed it in the development version (which is at this moment identical to the CRAN version with exception of this bug fix), so you can try it by installing it via devtools:

    devtools::install_github("stefan-m-lenz/JuliaConnectoR")

I hope that also your problem is fixed with this. Having blank spaces inside paths is very much a Windows thing. Please let me know whether this solves your issue.

**Comment by jgoodman55** [comment] 2021-01-23 21:02
Got it, I will give it a try. I also ran the function juliaSetupOk() and it returned true. Thanks for your help! If that doesn’t work, I’ll check the firewall settings and get back to you.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jgoodman55** [comment] 2021-01-25 15:18
Hello,


I wanted to let you know that I executed the command "remote::install_github("stefan-m-lenz/JuliaConnectoR")", and I am no longer getting the error. Thank you again for your help.



Best,



Jordan


Jordan Goodman, MS
Product Analyst, Solutions Delivery
jgoodman@arbormetrix.com<mailto:jgoodman@arbormetrix.com>
858-750-8155

ArborMetrix.com

ArborMetrix
Specify. Measure. Act.

**Comment by stefan-m-lenz** [comment] 2021-01-25 17:24
Great, thanks for the feedback and the bug report! I will submit the bug fix to CRAN soon.

**Closed as completed by stefan-m-lenz** 2021-01-25 17:24 UTC
